// Generated by scripts/generate-phone-countries.mjs; do not edit.
export const phoneCountries = [
  {
    "region": "PH",
    "callingCode": "63",
    "mainCountry": false,
    "name": "Philippines"
  },
  {
    "region": "AF",
    "callingCode": "93",
    "mainCountry": false,
    "name": "Afghanistan"
  },
  {
    "region": "AX",
    "callingCode": "358",
    "mainCountry": false,
    "name": "Åland Islands"
  },
  {
    "region": "AL",
    "callingCode": "355",
    "mainCountry": false,
    "name": "Albania"
  },
  {
    "region": "DZ",
    "callingCode": "213",
    "mainCountry": false,
    "name": "Algeria"
  },
  {
    "region": "AS",
    "callingCode": "1",
    "mainCountry": false,
    "name": "American Samoa"
  },
  {
    "region": "AD",
    "callingCode": "376",
    "mainCountry": false,
    "name": "Andorra"
  },
  {
    "region": "AO",
    "callingCode": "244",
    "mainCountry": false,
    "name": "Angola"
  },
  {
    "region": "AI",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Anguilla"
  },
  {
    "region": "AG",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Antigua & Barbuda"
  },
  {
    "region": "AR",
    "callingCode": "54",
    "mainCountry": false,
    "name": "Argentina"
  },
  {
    "region": "AM",
    "callingCode": "374",
    "mainCountry": false,
    "name": "Armenia"
  },
  {
    "region": "AW",
    "callingCode": "297",
    "mainCountry": false,
    "name": "Aruba"
  },
  {
    "region": "AC",
    "callingCode": "247",
    "mainCountry": false,
    "name": "Ascension Island"
  },
  {
    "region": "AU",
    "callingCode": "61",
    "mainCountry": true,
    "name": "Australia"
  },
  {
    "region": "AT",
    "callingCode": "43",
    "mainCountry": false,
    "name": "Austria"
  },
  {
    "region": "AZ",
    "callingCode": "994",
    "mainCountry": false,
    "name": "Azerbaijan"
  },
  {
    "region": "BS",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Bahamas"
  },
  {
    "region": "BH",
    "callingCode": "973",
    "mainCountry": false,
    "name": "Bahrain"
  },
  {
    "region": "BD",
    "callingCode": "880",
    "mainCountry": false,
    "name": "Bangladesh"
  },
  {
    "region": "BB",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Barbados"
  },
  {
    "region": "BY",
    "callingCode": "375",
    "mainCountry": false,
    "name": "Belarus"
  },
  {
    "region": "BE",
    "callingCode": "32",
    "mainCountry": false,
    "name": "Belgium"
  },
  {
    "region": "BZ",
    "callingCode": "501",
    "mainCountry": false,
    "name": "Belize"
  },
  {
    "region": "BJ",
    "callingCode": "229",
    "mainCountry": false,
    "name": "Benin"
  },
  {
    "region": "BM",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Bermuda"
  },
  {
    "region": "BT",
    "callingCode": "975",
    "mainCountry": false,
    "name": "Bhutan"
  },
  {
    "region": "BO",
    "callingCode": "591",
    "mainCountry": false,
    "name": "Bolivia"
  },
  {
    "region": "BA",
    "callingCode": "387",
    "mainCountry": false,
    "name": "Bosnia & Herzegovina"
  },
  {
    "region": "BW",
    "callingCode": "267",
    "mainCountry": false,
    "name": "Botswana"
  },
  {
    "region": "BR",
    "callingCode": "55",
    "mainCountry": false,
    "name": "Brazil"
  },
  {
    "region": "IO",
    "callingCode": "246",
    "mainCountry": false,
    "name": "British Indian Ocean Territory"
  },
  {
    "region": "VG",
    "callingCode": "1",
    "mainCountry": false,
    "name": "British Virgin Islands"
  },
  {
    "region": "BN",
    "callingCode": "673",
    "mainCountry": false,
    "name": "Brunei"
  },
  {
    "region": "BG",
    "callingCode": "359",
    "mainCountry": false,
    "name": "Bulgaria"
  },
  {
    "region": "BF",
    "callingCode": "226",
    "mainCountry": false,
    "name": "Burkina Faso"
  },
  {
    "region": "BI",
    "callingCode": "257",
    "mainCountry": false,
    "name": "Burundi"
  },
  {
    "region": "KH",
    "callingCode": "855",
    "mainCountry": false,
    "name": "Cambodia"
  },
  {
    "region": "CM",
    "callingCode": "237",
    "mainCountry": false,
    "name": "Cameroon"
  },
  {
    "region": "CA",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Canada"
  },
  {
    "region": "CV",
    "callingCode": "238",
    "mainCountry": false,
    "name": "Cape Verde"
  },
  {
    "region": "BQ",
    "callingCode": "599",
    "mainCountry": false,
    "name": "Caribbean Netherlands"
  },
  {
    "region": "KY",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Cayman Islands"
  },
  {
    "region": "CF",
    "callingCode": "236",
    "mainCountry": false,
    "name": "Central African Republic"
  },
  {
    "region": "TD",
    "callingCode": "235",
    "mainCountry": false,
    "name": "Chad"
  },
  {
    "region": "CL",
    "callingCode": "56",
    "mainCountry": false,
    "name": "Chile"
  },
  {
    "region": "CN",
    "callingCode": "86",
    "mainCountry": false,
    "name": "China"
  },
  {
    "region": "CX",
    "callingCode": "61",
    "mainCountry": false,
    "name": "Christmas Island"
  },
  {
    "region": "CC",
    "callingCode": "61",
    "mainCountry": false,
    "name": "Cocos (Keeling) Islands"
  },
  {
    "region": "CO",
    "callingCode": "57",
    "mainCountry": false,
    "name": "Colombia"
  },
  {
    "region": "KM",
    "callingCode": "269",
    "mainCountry": false,
    "name": "Comoros"
  },
  {
    "region": "CG",
    "callingCode": "242",
    "mainCountry": false,
    "name": "Congo - Brazzaville"
  },
  {
    "region": "CD",
    "callingCode": "243",
    "mainCountry": false,
    "name": "Congo - Kinshasa"
  },
  {
    "region": "CK",
    "callingCode": "682",
    "mainCountry": false,
    "name": "Cook Islands"
  },
  {
    "region": "CR",
    "callingCode": "506",
    "mainCountry": false,
    "name": "Costa Rica"
  },
  {
    "region": "CI",
    "callingCode": "225",
    "mainCountry": false,
    "name": "Côte d’Ivoire"
  },
  {
    "region": "HR",
    "callingCode": "385",
    "mainCountry": false,
    "name": "Croatia"
  },
  {
    "region": "CU",
    "callingCode": "53",
    "mainCountry": false,
    "name": "Cuba"
  },
  {
    "region": "CW",
    "callingCode": "599",
    "mainCountry": true,
    "name": "Curaçao"
  },
  {
    "region": "CY",
    "callingCode": "357",
    "mainCountry": false,
    "name": "Cyprus"
  },
  {
    "region": "CZ",
    "callingCode": "420",
    "mainCountry": false,
    "name": "Czechia"
  },
  {
    "region": "DK",
    "callingCode": "45",
    "mainCountry": false,
    "name": "Denmark"
  },
  {
    "region": "DJ",
    "callingCode": "253",
    "mainCountry": false,
    "name": "Djibouti"
  },
  {
    "region": "DM",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Dominica"
  },
  {
    "region": "DO",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Dominican Republic"
  },
  {
    "region": "EC",
    "callingCode": "593",
    "mainCountry": false,
    "name": "Ecuador"
  },
  {
    "region": "EG",
    "callingCode": "20",
    "mainCountry": false,
    "name": "Egypt"
  },
  {
    "region": "SV",
    "callingCode": "503",
    "mainCountry": false,
    "name": "El Salvador"
  },
  {
    "region": "GQ",
    "callingCode": "240",
    "mainCountry": false,
    "name": "Equatorial Guinea"
  },
  {
    "region": "ER",
    "callingCode": "291",
    "mainCountry": false,
    "name": "Eritrea"
  },
  {
    "region": "EE",
    "callingCode": "372",
    "mainCountry": false,
    "name": "Estonia"
  },
  {
    "region": "SZ",
    "callingCode": "268",
    "mainCountry": false,
    "name": "Eswatini"
  },
  {
    "region": "ET",
    "callingCode": "251",
    "mainCountry": false,
    "name": "Ethiopia"
  },
  {
    "region": "FK",
    "callingCode": "500",
    "mainCountry": false,
    "name": "Falkland Islands"
  },
  {
    "region": "FO",
    "callingCode": "298",
    "mainCountry": false,
    "name": "Faroe Islands"
  },
  {
    "region": "FJ",
    "callingCode": "679",
    "mainCountry": false,
    "name": "Fiji"
  },
  {
    "region": "FI",
    "callingCode": "358",
    "mainCountry": true,
    "name": "Finland"
  },
  {
    "region": "FR",
    "callingCode": "33",
    "mainCountry": false,
    "name": "France"
  },
  {
    "region": "GF",
    "callingCode": "594",
    "mainCountry": false,
    "name": "French Guiana"
  },
  {
    "region": "PF",
    "callingCode": "689",
    "mainCountry": false,
    "name": "French Polynesia"
  },
  {
    "region": "GA",
    "callingCode": "241",
    "mainCountry": false,
    "name": "Gabon"
  },
  {
    "region": "GM",
    "callingCode": "220",
    "mainCountry": false,
    "name": "Gambia"
  },
  {
    "region": "GE",
    "callingCode": "995",
    "mainCountry": false,
    "name": "Georgia"
  },
  {
    "region": "DE",
    "callingCode": "49",
    "mainCountry": false,
    "name": "Germany"
  },
  {
    "region": "GH",
    "callingCode": "233",
    "mainCountry": false,
    "name": "Ghana"
  },
  {
    "region": "GI",
    "callingCode": "350",
    "mainCountry": false,
    "name": "Gibraltar"
  },
  {
    "region": "GR",
    "callingCode": "30",
    "mainCountry": false,
    "name": "Greece"
  },
  {
    "region": "GL",
    "callingCode": "299",
    "mainCountry": false,
    "name": "Greenland"
  },
  {
    "region": "GD",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Grenada"
  },
  {
    "region": "GP",
    "callingCode": "590",
    "mainCountry": true,
    "name": "Guadeloupe"
  },
  {
    "region": "GU",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Guam"
  },
  {
    "region": "GT",
    "callingCode": "502",
    "mainCountry": false,
    "name": "Guatemala"
  },
  {
    "region": "GG",
    "callingCode": "44",
    "mainCountry": false,
    "name": "Guernsey"
  },
  {
    "region": "GN",
    "callingCode": "224",
    "mainCountry": false,
    "name": "Guinea"
  },
  {
    "region": "GW",
    "callingCode": "245",
    "mainCountry": false,
    "name": "Guinea-Bissau"
  },
  {
    "region": "GY",
    "callingCode": "592",
    "mainCountry": false,
    "name": "Guyana"
  },
  {
    "region": "HT",
    "callingCode": "509",
    "mainCountry": false,
    "name": "Haiti"
  },
  {
    "region": "HN",
    "callingCode": "504",
    "mainCountry": false,
    "name": "Honduras"
  },
  {
    "region": "HK",
    "callingCode": "852",
    "mainCountry": false,
    "name": "Hong Kong SAR China"
  },
  {
    "region": "HU",
    "callingCode": "36",
    "mainCountry": false,
    "name": "Hungary"
  },
  {
    "region": "IS",
    "callingCode": "354",
    "mainCountry": false,
    "name": "Iceland"
  },
  {
    "region": "IN",
    "callingCode": "91",
    "mainCountry": false,
    "name": "India"
  },
  {
    "region": "ID",
    "callingCode": "62",
    "mainCountry": false,
    "name": "Indonesia"
  },
  {
    "region": "IR",
    "callingCode": "98",
    "mainCountry": false,
    "name": "Iran"
  },
  {
    "region": "IQ",
    "callingCode": "964",
    "mainCountry": false,
    "name": "Iraq"
  },
  {
    "region": "IE",
    "callingCode": "353",
    "mainCountry": false,
    "name": "Ireland"
  },
  {
    "region": "IM",
    "callingCode": "44",
    "mainCountry": false,
    "name": "Isle of Man"
  },
  {
    "region": "IL",
    "callingCode": "972",
    "mainCountry": false,
    "name": "Israel"
  },
  {
    "region": "IT",
    "callingCode": "39",
    "mainCountry": true,
    "name": "Italy"
  },
  {
    "region": "JM",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Jamaica"
  },
  {
    "region": "JP",
    "callingCode": "81",
    "mainCountry": false,
    "name": "Japan"
  },
  {
    "region": "JE",
    "callingCode": "44",
    "mainCountry": false,
    "name": "Jersey"
  },
  {
    "region": "JO",
    "callingCode": "962",
    "mainCountry": false,
    "name": "Jordan"
  },
  {
    "region": "KZ",
    "callingCode": "7",
    "mainCountry": false,
    "name": "Kazakhstan"
  },
  {
    "region": "KE",
    "callingCode": "254",
    "mainCountry": false,
    "name": "Kenya"
  },
  {
    "region": "KI",
    "callingCode": "686",
    "mainCountry": false,
    "name": "Kiribati"
  },
  {
    "region": "XK",
    "callingCode": "383",
    "mainCountry": false,
    "name": "Kosovo"
  },
  {
    "region": "KW",
    "callingCode": "965",
    "mainCountry": false,
    "name": "Kuwait"
  },
  {
    "region": "KG",
    "callingCode": "996",
    "mainCountry": false,
    "name": "Kyrgyzstan"
  },
  {
    "region": "LA",
    "callingCode": "856",
    "mainCountry": false,
    "name": "Laos"
  },
  {
    "region": "LV",
    "callingCode": "371",
    "mainCountry": false,
    "name": "Latvia"
  },
  {
    "region": "LB",
    "callingCode": "961",
    "mainCountry": false,
    "name": "Lebanon"
  },
  {
    "region": "LS",
    "callingCode": "266",
    "mainCountry": false,
    "name": "Lesotho"
  },
  {
    "region": "LR",
    "callingCode": "231",
    "mainCountry": false,
    "name": "Liberia"
  },
  {
    "region": "LY",
    "callingCode": "218",
    "mainCountry": false,
    "name": "Libya"
  },
  {
    "region": "LI",
    "callingCode": "423",
    "mainCountry": false,
    "name": "Liechtenstein"
  },
  {
    "region": "LT",
    "callingCode": "370",
    "mainCountry": false,
    "name": "Lithuania"
  },
  {
    "region": "LU",
    "callingCode": "352",
    "mainCountry": false,
    "name": "Luxembourg"
  },
  {
    "region": "MO",
    "callingCode": "853",
    "mainCountry": false,
    "name": "Macao SAR China"
  },
  {
    "region": "MG",
    "callingCode": "261",
    "mainCountry": false,
    "name": "Madagascar"
  },
  {
    "region": "MW",
    "callingCode": "265",
    "mainCountry": false,
    "name": "Malawi"
  },
  {
    "region": "MY",
    "callingCode": "60",
    "mainCountry": false,
    "name": "Malaysia"
  },
  {
    "region": "MV",
    "callingCode": "960",
    "mainCountry": false,
    "name": "Maldives"
  },
  {
    "region": "ML",
    "callingCode": "223",
    "mainCountry": false,
    "name": "Mali"
  },
  {
    "region": "MT",
    "callingCode": "356",
    "mainCountry": false,
    "name": "Malta"
  },
  {
    "region": "MH",
    "callingCode": "692",
    "mainCountry": false,
    "name": "Marshall Islands"
  },
  {
    "region": "MQ",
    "callingCode": "596",
    "mainCountry": false,
    "name": "Martinique"
  },
  {
    "region": "MR",
    "callingCode": "222",
    "mainCountry": false,
    "name": "Mauritania"
  },
  {
    "region": "MU",
    "callingCode": "230",
    "mainCountry": false,
    "name": "Mauritius"
  },
  {
    "region": "YT",
    "callingCode": "262",
    "mainCountry": false,
    "name": "Mayotte"
  },
  {
    "region": "MX",
    "callingCode": "52",
    "mainCountry": false,
    "name": "Mexico"
  },
  {
    "region": "FM",
    "callingCode": "691",
    "mainCountry": false,
    "name": "Micronesia"
  },
  {
    "region": "MD",
    "callingCode": "373",
    "mainCountry": false,
    "name": "Moldova"
  },
  {
    "region": "MC",
    "callingCode": "377",
    "mainCountry": false,
    "name": "Monaco"
  },
  {
    "region": "MN",
    "callingCode": "976",
    "mainCountry": false,
    "name": "Mongolia"
  },
  {
    "region": "ME",
    "callingCode": "382",
    "mainCountry": false,
    "name": "Montenegro"
  },
  {
    "region": "MS",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Montserrat"
  },
  {
    "region": "MA",
    "callingCode": "212",
    "mainCountry": true,
    "name": "Morocco"
  },
  {
    "region": "MZ",
    "callingCode": "258",
    "mainCountry": false,
    "name": "Mozambique"
  },
  {
    "region": "MM",
    "callingCode": "95",
    "mainCountry": false,
    "name": "Myanmar (Burma)"
  },
  {
    "region": "NA",
    "callingCode": "264",
    "mainCountry": false,
    "name": "Namibia"
  },
  {
    "region": "NR",
    "callingCode": "674",
    "mainCountry": false,
    "name": "Nauru"
  },
  {
    "region": "NP",
    "callingCode": "977",
    "mainCountry": false,
    "name": "Nepal"
  },
  {
    "region": "NL",
    "callingCode": "31",
    "mainCountry": false,
    "name": "Netherlands"
  },
  {
    "region": "NC",
    "callingCode": "687",
    "mainCountry": false,
    "name": "New Caledonia"
  },
  {
    "region": "NZ",
    "callingCode": "64",
    "mainCountry": false,
    "name": "New Zealand"
  },
  {
    "region": "NI",
    "callingCode": "505",
    "mainCountry": false,
    "name": "Nicaragua"
  },
  {
    "region": "NE",
    "callingCode": "227",
    "mainCountry": false,
    "name": "Niger"
  },
  {
    "region": "NG",
    "callingCode": "234",
    "mainCountry": false,
    "name": "Nigeria"
  },
  {
    "region": "NU",
    "callingCode": "683",
    "mainCountry": false,
    "name": "Niue"
  },
  {
    "region": "NF",
    "callingCode": "672",
    "mainCountry": false,
    "name": "Norfolk Island"
  },
  {
    "region": "KP",
    "callingCode": "850",
    "mainCountry": false,
    "name": "North Korea"
  },
  {
    "region": "MK",
    "callingCode": "389",
    "mainCountry": false,
    "name": "North Macedonia"
  },
  {
    "region": "MP",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Northern Mariana Islands"
  },
  {
    "region": "NO",
    "callingCode": "47",
    "mainCountry": true,
    "name": "Norway"
  },
  {
    "region": "OM",
    "callingCode": "968",
    "mainCountry": false,
    "name": "Oman"
  },
  {
    "region": "PK",
    "callingCode": "92",
    "mainCountry": false,
    "name": "Pakistan"
  },
  {
    "region": "PW",
    "callingCode": "680",
    "mainCountry": false,
    "name": "Palau"
  },
  {
    "region": "PS",
    "callingCode": "970",
    "mainCountry": false,
    "name": "Palestinian Territories"
  },
  {
    "region": "PA",
    "callingCode": "507",
    "mainCountry": false,
    "name": "Panama"
  },
  {
    "region": "PG",
    "callingCode": "675",
    "mainCountry": false,
    "name": "Papua New Guinea"
  },
  {
    "region": "PY",
    "callingCode": "595",
    "mainCountry": false,
    "name": "Paraguay"
  },
  {
    "region": "PE",
    "callingCode": "51",
    "mainCountry": false,
    "name": "Peru"
  },
  {
    "region": "PL",
    "callingCode": "48",
    "mainCountry": false,
    "name": "Poland"
  },
  {
    "region": "PT",
    "callingCode": "351",
    "mainCountry": false,
    "name": "Portugal"
  },
  {
    "region": "PR",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Puerto Rico"
  },
  {
    "region": "QA",
    "callingCode": "974",
    "mainCountry": false,
    "name": "Qatar"
  },
  {
    "region": "RE",
    "callingCode": "262",
    "mainCountry": true,
    "name": "Réunion"
  },
  {
    "region": "RO",
    "callingCode": "40",
    "mainCountry": false,
    "name": "Romania"
  },
  {
    "region": "RU",
    "callingCode": "7",
    "mainCountry": true,
    "name": "Russia"
  },
  {
    "region": "RW",
    "callingCode": "250",
    "mainCountry": false,
    "name": "Rwanda"
  },
  {
    "region": "WS",
    "callingCode": "685",
    "mainCountry": false,
    "name": "Samoa"
  },
  {
    "region": "SM",
    "callingCode": "378",
    "mainCountry": false,
    "name": "San Marino"
  },
  {
    "region": "ST",
    "callingCode": "239",
    "mainCountry": false,
    "name": "São Tomé & Príncipe"
  },
  {
    "region": "SA",
    "callingCode": "966",
    "mainCountry": false,
    "name": "Saudi Arabia"
  },
  {
    "region": "SN",
    "callingCode": "221",
    "mainCountry": false,
    "name": "Senegal"
  },
  {
    "region": "RS",
    "callingCode": "381",
    "mainCountry": false,
    "name": "Serbia"
  },
  {
    "region": "SC",
    "callingCode": "248",
    "mainCountry": false,
    "name": "Seychelles"
  },
  {
    "region": "SL",
    "callingCode": "232",
    "mainCountry": false,
    "name": "Sierra Leone"
  },
  {
    "region": "SG",
    "callingCode": "65",
    "mainCountry": false,
    "name": "Singapore"
  },
  {
    "region": "SX",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Sint Maarten"
  },
  {
    "region": "SK",
    "callingCode": "421",
    "mainCountry": false,
    "name": "Slovakia"
  },
  {
    "region": "SI",
    "callingCode": "386",
    "mainCountry": false,
    "name": "Slovenia"
  },
  {
    "region": "SB",
    "callingCode": "677",
    "mainCountry": false,
    "name": "Solomon Islands"
  },
  {
    "region": "SO",
    "callingCode": "252",
    "mainCountry": false,
    "name": "Somalia"
  },
  {
    "region": "ZA",
    "callingCode": "27",
    "mainCountry": false,
    "name": "South Africa"
  },
  {
    "region": "KR",
    "callingCode": "82",
    "mainCountry": false,
    "name": "South Korea"
  },
  {
    "region": "SS",
    "callingCode": "211",
    "mainCountry": false,
    "name": "South Sudan"
  },
  {
    "region": "ES",
    "callingCode": "34",
    "mainCountry": false,
    "name": "Spain"
  },
  {
    "region": "LK",
    "callingCode": "94",
    "mainCountry": false,
    "name": "Sri Lanka"
  },
  {
    "region": "BL",
    "callingCode": "590",
    "mainCountry": false,
    "name": "St. Barthélemy"
  },
  {
    "region": "SH",
    "callingCode": "290",
    "mainCountry": true,
    "name": "St. Helena"
  },
  {
    "region": "KN",
    "callingCode": "1",
    "mainCountry": false,
    "name": "St. Kitts & Nevis"
  },
  {
    "region": "LC",
    "callingCode": "1",
    "mainCountry": false,
    "name": "St. Lucia"
  },
  {
    "region": "MF",
    "callingCode": "590",
    "mainCountry": false,
    "name": "St. Martin"
  },
  {
    "region": "PM",
    "callingCode": "508",
    "mainCountry": false,
    "name": "St. Pierre & Miquelon"
  },
  {
    "region": "VC",
    "callingCode": "1",
    "mainCountry": false,
    "name": "St. Vincent & Grenadines"
  },
  {
    "region": "SD",
    "callingCode": "249",
    "mainCountry": false,
    "name": "Sudan"
  },
  {
    "region": "SR",
    "callingCode": "597",
    "mainCountry": false,
    "name": "Suriname"
  },
  {
    "region": "SJ",
    "callingCode": "47",
    "mainCountry": false,
    "name": "Svalbard & Jan Mayen"
  },
  {
    "region": "SE",
    "callingCode": "46",
    "mainCountry": false,
    "name": "Sweden"
  },
  {
    "region": "CH",
    "callingCode": "41",
    "mainCountry": false,
    "name": "Switzerland"
  },
  {
    "region": "SY",
    "callingCode": "963",
    "mainCountry": false,
    "name": "Syria"
  },
  {
    "region": "TW",
    "callingCode": "886",
    "mainCountry": false,
    "name": "Taiwan"
  },
  {
    "region": "TJ",
    "callingCode": "992",
    "mainCountry": false,
    "name": "Tajikistan"
  },
  {
    "region": "TZ",
    "callingCode": "255",
    "mainCountry": false,
    "name": "Tanzania"
  },
  {
    "region": "TH",
    "callingCode": "66",
    "mainCountry": false,
    "name": "Thailand"
  },
  {
    "region": "TL",
    "callingCode": "670",
    "mainCountry": false,
    "name": "Timor-Leste"
  },
  {
    "region": "TG",
    "callingCode": "228",
    "mainCountry": false,
    "name": "Togo"
  },
  {
    "region": "TK",
    "callingCode": "690",
    "mainCountry": false,
    "name": "Tokelau"
  },
  {
    "region": "TO",
    "callingCode": "676",
    "mainCountry": false,
    "name": "Tonga"
  },
  {
    "region": "TT",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Trinidad & Tobago"
  },
  {
    "region": "TA",
    "callingCode": "290",
    "mainCountry": false,
    "name": "Tristan da Cunha"
  },
  {
    "region": "TN",
    "callingCode": "216",
    "mainCountry": false,
    "name": "Tunisia"
  },
  {
    "region": "TR",
    "callingCode": "90",
    "mainCountry": false,
    "name": "Türkiye"
  },
  {
    "region": "TM",
    "callingCode": "993",
    "mainCountry": false,
    "name": "Turkmenistan"
  },
  {
    "region": "TC",
    "callingCode": "1",
    "mainCountry": false,
    "name": "Turks & Caicos Islands"
  },
  {
    "region": "TV",
    "callingCode": "688",
    "mainCountry": false,
    "name": "Tuvalu"
  },
  {
    "region": "VI",
    "callingCode": "1",
    "mainCountry": false,
    "name": "U.S. Virgin Islands"
  },
  {
    "region": "UG",
    "callingCode": "256",
    "mainCountry": false,
    "name": "Uganda"
  },
  {
    "region": "UA",
    "callingCode": "380",
    "mainCountry": false,
    "name": "Ukraine"
  },
  {
    "region": "AE",
    "callingCode": "971",
    "mainCountry": false,
    "name": "United Arab Emirates"
  },
  {
    "region": "GB",
    "callingCode": "44",
    "mainCountry": true,
    "name": "United Kingdom"
  },
  {
    "region": "US",
    "callingCode": "1",
    "mainCountry": true,
    "name": "United States"
  },
  {
    "region": "UY",
    "callingCode": "598",
    "mainCountry": false,
    "name": "Uruguay"
  },
  {
    "region": "UZ",
    "callingCode": "998",
    "mainCountry": false,
    "name": "Uzbekistan"
  },
  {
    "region": "VU",
    "callingCode": "678",
    "mainCountry": false,
    "name": "Vanuatu"
  },
  {
    "region": "VA",
    "callingCode": "39",
    "mainCountry": false,
    "name": "Vatican City"
  },
  {
    "region": "VE",
    "callingCode": "58",
    "mainCountry": false,
    "name": "Venezuela"
  },
  {
    "region": "VN",
    "callingCode": "84",
    "mainCountry": false,
    "name": "Vietnam"
  },
  {
    "region": "WF",
    "callingCode": "681",
    "mainCountry": false,
    "name": "Wallis & Futuna"
  },
  {
    "region": "EH",
    "callingCode": "212",
    "mainCountry": false,
    "name": "Western Sahara"
  },
  {
    "region": "YE",
    "callingCode": "967",
    "mainCountry": false,
    "name": "Yemen"
  },
  {
    "region": "ZM",
    "callingCode": "260",
    "mainCountry": false,
    "name": "Zambia"
  },
  {
    "region": "ZW",
    "callingCode": "263",
    "mainCountry": false,
    "name": "Zimbabwe"
  }
] as const
